import DeepArithmetic.Foundation.Lists.PureAxioms
import DeepArithmetic.Foundation.Trees.PureAxioms
import DeepArithmetic.Semantics.Peano.Connection
import DeepArithmetic.Semantics.Lists.Connection
import DeepArithmetic.Semantics.Trees.Connection
import DeepArithmetic.Semantics.Lists.Computability
import DeepArithmetic.Semantics.Trees.Computability
import DeepArithmetic.Semantics.Peano.Computability
import DeepArithmetic.LogicAbstraction.SyntacticSugar
import DeepArithmetic.LogicAbstraction.SetTheory
import DeepArithmetic.LogicAbstraction.Arithmetic
import DeepArithmetic.LogicAbstraction.PeanoModel
import DeepArithmetic.LogicAbstraction.Tactics
import DeepArithmetic.LogicAbstraction.Proofs
import DeepArithmetic.LogicAbstraction.ArithmeticAddProofs
import DeepArithmetic.LogicAbstraction.ArithmeticMultProofs
import DeepArithmetic.LogicAbstraction.Lists
import DeepArithmetic.LogicAbstraction.Trees

def hello := "world"
